/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FileId = IDL.Text;
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'contentType' : IDL.Text,
  'size' : IDL.Nat,
  'uploadTimestamp' : Time,
  'filename' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getFile' : IDL.Func(
      [FileId],
      [
        IDL.Opt(
          IDL.Record({ 'metadata' : FileMetadata, 'blob' : ExternalBlob })
        ),
      ],
      ['query'],
    ),
  'listFiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'metadata' : FileMetadata, 'fileId' : FileId }))],
      ['query'],
    ),
  'uploadFile' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
      [FileId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FileId = IDL.Text;
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'uploadTimestamp' : Time,
    'filename' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getFile' : IDL.Func(
        [FileId],
        [
          IDL.Opt(
            IDL.Record({ 'metadata' : FileMetadata, 'blob' : ExternalBlob })
          ),
        ],
        ['query'],
      ),
    'listFiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'metadata' : FileMetadata, 'fileId' : FileId }))],
        ['query'],
      ),
    'uploadFile' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
        [FileId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };